---
- name: copy files
  hosts: sweats
  become: yes
  
  tasks:
    - name: copy files
      copy:
        src: /tmp/copyfile.txt
        dest: /tmp/copyfile.txt
        owner: ec2-user
        group: ec2-user
        mode: '0640'

    - name: copy remote files
      copy: 
        src: /tmp/random.txt
        dest: /mnt/random.txt
        owner: ec2-user
        group: ec2-user
        mode: '0600'
        remote_src: yes